### ISSUE TITLE
MSI error when installing on Windows Server 2008/2012R2

### ISSUE THREAD

**Issue by asgcedricl** [rottedfrog/TextReplace#1]
When installing the MSI "TextReplace.Test.Setup" on Windows Server (2008R2/2012R2), an error occured: A DLL required for this install to complete could not be run"

![error_msi](https://user-images.githubusercontent.com/6000912/27275671-c41d64ee-54d8-11e7-9b5a-9fc38d3ba460.png)

**Comment by rottedfrog** [comment]
I'm not seeing the same issue when I build and test (I am using Windows 10 though, but there should be no difference). TextReplace.Test.Setup isn't meant to be run on it's own, it's a basic scaffold I wrote to run the tests for the C++ custom action project. That being said the unit tests didn't all work in the checked in version, so I have tidied that up, and removed a dodgy debug dialog from the Custom Action.

Can you try getting the latest version and **rebuilding** one project at a time, in the following order:

TextReplaceCA
TextReplace.WixLib
TextReplace
TextReplace.Test.Setup
TextReplaceCA.Tests

If you are having problems with a non-test setup, then can you install with msi verbose logging (using a command line similar to "msiexec /l*v loggy.log /i mysetup.msi") and then create a new issue with that log attached so I can see exactly what has happened.
