### ISSUE TITLE
Not able to build TextReplaceCA in VS 2017 Community Edition

### ISSUE THREAD

**Issue by clustor** [rottedfrog/TextReplace#4]
I get the following errors while compiling msihelper.cpp & TextReplaceCA.cpp

1>c:work\repos\textreplace-master\textreplaceca\msihelper.h(310): error C2039: 'Encode': is not a member of 'MsiViewEncoder'
1>c:\work\repos\textreplace-master\textreplaceca\msihelper.h(302): note: see declaration of 'MsiViewEncoder'

1) I have tried changing the definition from

  std::wstring MsiViewEncoder::Encode(MsiView &view, Predicate filterPredicate) const
to
  std::wstring Encode(MsiView &view, Predicate filterPredicate) const

but there are more issues.

2) I have tried moving the Encode function to msihelper.cpp but I get linker errors about missing "Encode".

I haven't done C++ in more than decade so I thought I would ask for help. None of the C2039 error references from Google helped :( 

======
I have copied TextReplace.dll to my project and added it as a Wix Reference. But build fails as it is looking for TextReplaceCA.dll. Based on the instructions I thought only TextReplace.dll is needed.

3>C:\Work\Repos\TextReplace-master\TextReplace.WixLib\Library.wxs(4,0): error LGHT0103: The system cannot find the file 'C:\Work\Repos\TextReplace-master\Debug\TextReplaceCA.dll'.

**Comment by rottedfrog** [comment]
TextReplace.dll is all that is needed, but the CA dll is embedded in there via the wixlib, so if that doesn’t build everything goes screwy.

I have a clean build on my machine corresponding to the latest commit, and I’m using VS 2017 community with update 5. Making your change doesn’t make any difference to the compile, although it gets rid of a redundant qualifier. 

Is there anything else you can see in your build that could give some insight? Have you made any other changes?

**Comment by clustor** [comment]
I started with a fresh git clone but the solution file had to be updated to
the latest SDK and toolset I have on my Windows 10 machine.


[image: image.png]

My VS 2017 version is 15.5.2.


$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   TestReplaceCA.Test/TestReplaceCA.Test.vcxproj
        modified:   TextReplace/TextReplace.csproj
        modified:   TextReplaceCA/TextReplaceCA.vcxproj

The only change I made is to point to Wix Toolset 3.11.

$ git diff TextReplace/TextReplace.csproj
diff --git a/TextReplace/TextReplace.csproj b/TextReplace/TextReplace.csproj
index f720eb9..9c17947 100644
--- a/TextReplace/TextReplace.csproj
+++ b/TextReplace/TextReplace.csproj
@@ -35,7 +35,7 @@
     <Reference Include="System.Data" />
     <Reference Include="System.Xml" />
     <Reference Include="wix">
-      <HintPath>C:\Program Files (x86)\WiX Toolset
v3.10\bin\wix.dll</HintPath>
+      <HintPath>C:\Program Files (x86)\WiX Toolset
v3.11\bin\wix.dll</HintPath>
     </Reference>
   </ItemGroup>
   <ItemGroup>

Thanks for your prompt assistance.

**Comment by rottedfrog** [comment]
Apologies for the delay, I've had a look - looks like the compiler is more stringent about the signature for != in iterators for VS2017 (once I changed the target - for some reason I didn't pick up that vital clue when I read your log the first time). It was a very simple fix. Get latest from master and try again -
 everything should build now when you update the target.
